### ISSUE TITLE
Brew upgrade fail

### ISSUE THREAD

**Issue by alphatroya** [Nonchalant/AppIcon#35]
There is an error during upgrade action through brew

<img width="829" alt="2017-11-29 17 00 57" src="https://user-images.githubusercontent.com/4927633/33378770-f288e5c8-d526-11e7-8836-1c53a2164acd.png">

**Comment by Nonchalant** [comment]
@alphatroya 
Thank you for reporting your issue. And I happend same problem :bow:
So I upgraded [homebrew-appicon](https://github.com/Nonchalant/homebrew-appicon/commit/7007f9a839b5cf2cf2e76a556d5561092ddb842c) to set correct sha256 🚀 

You should try `brew upgrade && brew cleanup` again! 👍

**Comment by alphatroya** [comment]
Unfortunately after try to run `brew install Nonchalant/appicon/appicon` another error appeared 

```
❯ brew install Nonchalant/appicon/appicon
Updating Homebrew...
==> Installing appicon from nonchalant/appicon
==> Downloading https://github.com/Nonchalant/AppIcon/archive/0.3.2.tar.gz
==> Downloading from https://codeload.github.com/Nonchalant/AppIcon/tar.gz/0.3.2
######################################################################## 100,0%
==> make install PREFIX=/usr/local/Cellar/appicon/0.3.2
Last 15 lines from /Users/alphatroya/Library/Logs/Homebrew/appicon/01.make:
2017-11-30 09:21:33 +0300

make
install
PREFIX=/usr/local/Cellar/appicon/0.3.2

swift build -c release -Xswiftc -static-stdlib
error: manifest parse error(s):
sandbox-exec: sandbox_apply_container: Operation not permitted
make: *** [build] Error 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/nonchalant/homebrew-appicon/issues

/usr/local/Homebrew/Library/Homebrew/utils/github.rb:210:in `raise_api_error': GitHub  (GitHub::AuthenticationFailedError)
The GitHub credentials in the macOS keychain may be invalid.
Clear them with:
  printf "protocol=https\nhost=github.com\n" | git credential-osxkeychain erase
Or create a personal access token:
  https://github.com/settings/tokens/new?scopes=gist,public_repo&description=Homebrew
and then set the token as: export HOMEBREW_GITHUB_API_TOKEN="your_new_token"
        from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:178:in `open'
        from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:278:in `search'
        from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:225:in `search_issues'
        from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:238:in `issues_for_formula'
        from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:369:in `fetch_issues'
        from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:365:in `issues'
        from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:419:in `dump'
        from /usr/local/Homebrew/Library/Homebrew/brew.rb:138:in `rescue in <main>'
        from /usr/local/Homebrew/Library/Homebrew/brew.rb:30:in `<main>'
```

**Comment by Nonchalant** [comment]
@alphatroya
This error is occured for High Sierra. I updated AppIcon (0.3.3) to fix bugs 🚀 

You should try `brew install Nonchalant/appicon/appicon` again. Thank you 👍

**Comment by alphatroya** [comment]
Yes, now it works well, thanks!
